server:
  port: 8761                    # 指定该Eureka实例的端口

eureka:
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: false
    fetchRegistry: false
  server:
      wait-time-in-ms-when-sync-empty: 0

security:
  basic:
    enabled: true #开启基于Http Basic认证
  user:
    name: maopanpan
    password: 123456